### ISSUE TITLE
Drop MongoDB

### ISSUE THREAD

**Issue by danielsarsi** [OpenRCT2/master-server#4]
I used MongoDB for years in many projects, but I'm seeing a lot of articles criticizing it with very good reasons (http://cryto.net/~joepie91/blog/2015/07/19/why-you-should-never-ever-ever-use-mongodb/).
A relational database seems too fit better in this case.

**Comment by IntelOrca** [comment]
Relational databases require more maintenance and are not good when the schema frequently changes which is likely to happen for something like this.

**Comment by danielsarsi** [comment]
MongoDB doesn't even require setting a schema actually, CouchDB as well.
But, I do agree keeping it until multiplayer in OpenRCT2 get stable enough.

**Comment by IntelOrca** [comment]
> MongoDB doesn't even require setting a schema actually

That is my point.

**Comment by danielsarsi** [comment]
Mongoose uses schemas 😁
